AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for Tanzent backend application

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  SharedCodeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: codeLayer
      Description: share code layer to be used for all Lines lambda functions
      ContentUri: ../shared-layer/
      CompatibleRuntimes:
        - python3.9
      LicenseInfo: MIT
      RetentionPolicy: Retain

  LinesApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: Tanzent API
        paths:
          /line/{lineId}:
            get:
              security:
                - FirebaseJWTAuthorizer: []
          /allLines/{userId}:
            get:
              security:
                - FirebaseJWTAuthorizer: []
          /writer:
            post:
              security:
                - FirebaseJWTAuthorizer: []
          /fetchCircles:
            post:
              security:
                - FirebaseJWTAuthorizer: []
          /deleteLine/{lineId}:
            delete:
              security:
                - FirebaseJWTAuthorizer: []
          /updateCircle:
            put:
              security:
                - FirebaseJWTAuthorizer: []
          /fetchUpdates:
            post:
              security:
                - FirebaseJWTAuthorizer: []
          /fetchHomeWidgets:
            post:
              security:
                - FirebaseJWTAuthorizer: []
          /updateHomeWidgets:
            post:
              security:
                - FirebaseJWTAuthorizer: []
          /deleteHomeWidget/{id}:
            delete:
              security:
                - FirebaseJWTAuthorizer: []
        components:
          securitySchemes:
            FirebaseJWTAuthorizer:
              type: http
              scheme: bearer
              bearerFormat: JWT
              x-amazon-apigateway-authorizer:
                type: jwt
                jwtConfiguration:
                  issuer: https://securetoken.google.com/tazent-backend
                  audience:
                    - tanzent-backend
                identitySource: $request.header.Authorization

  # Lambda Functions (without Events as they're now defined in the API)
  LinesReaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: LinesReader/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedCodeLayer
      Runtime: python3.9
      Role: arn:aws:iam::107207560024:role/TanzentLambdaRole
      Architectures:
        - x86_64
      Events:
        LinesApiGETlinelineId:
          Type: HttpApi
          Properties:
            Path: /line/{lineId}
            Method: GET
            ApiId: !Ref LinesApi
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000

  LinesReaderAllFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: LinesReaderAll/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedCodeLayer
      Runtime: python3.9
      Role: arn:aws:iam::107207560024:role/TanzentLambdaRole
      Architectures:
        - x86_64
      Events:
        LinesApiGETallLinesuserId:
          Type: HttpApi
          Properties:
            Path: /allLines/{userId}
            Method: GET
            ApiId: !Ref LinesApi
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000

  LinesWriterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: LinesWriter/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedCodeLayer
      Runtime: python3.9
      Role: arn:aws:iam::107207560024:role/TanzentLambdaRole
      Architectures:
        - x86_64
      Events:
        LinesApiPOSTwriter:
          Type: HttpApi
          Properties:
            Path: /writer
            Method: POST
            ApiId: !Ref LinesApi
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000

  CirclesFetcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: CirclesFetcher/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedCodeLayer
      Runtime: python3.9
      Role: arn:aws:iam::107207560024:role/TanzentLambdaRole
      Architectures:
        - x86_64
      Events:
        LinesApiPOSTfetchCircles:
          Type: HttpApi
          Properties:
            Path: /fetchCircles
            Method: POST
            ApiId: !Ref LinesApi
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000

  LinesDeleterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: LinesDeleter/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedCodeLayer
      Runtime: python3.9
      Role: arn:aws:iam::107207560024:role/TanzentLambdaRole
      Architectures:
        - x86_64
      Events:
        LinesApiDELETEdeleteLinelineId:
          Type: HttpApi
          Properties:
            Path: /deleteLine/{lineId}
            Method: DELETE
            ApiId: !Ref LinesApi
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000

  CircleUpdaterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: CirclesUpdater/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedCodeLayer
      Runtime: python3.9
      Role: arn:aws:iam::107207560024:role/TanzentLambdaRole
      Architectures:
        - x86_64
      Events:
        LinesApiPUTupdateCircle:
          Type: HttpApi
          Properties:
            Path: /updateCircle
            Method: PUT
            ApiId: !Ref LinesApi
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000

  FetchUpdatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: FetchUpdates/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedCodeLayer
      Runtime: python3.9
      Role: arn:aws:iam::107207560024:role/TanzentLambdaRole
      Architectures:
        - x86_64
      Events:
        LinesApiPOSTfetchUpdates:
          Type: HttpApi
          Properties:
            Path: /fetchUpdates
            Method: POST
            ApiId: !Ref LinesApi
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000

  HomeWidgetsFetcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HomeWidgetsFetcher/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedCodeLayer
      Runtime: python3.9
      Role: arn:aws:iam::107207560024:role/TanzentLambdaRole
      Architectures:
        - x86_64
      Events:
        LinesApiPOSTfetchHomeWidgets:
          Type: HttpApi
          Properties:
            Path: /fetchHomeWidgets
            Method: POST
            ApiId: !Ref LinesApi
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000

  HomeWidgetsUpdaterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HomeWidgetsUpdater/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedCodeLayer
      Runtime: python3.9
      Role: arn:aws:iam::107207560024:role/TanzentLambdaRole
      Architectures:
        - x86_64
      Events:
        LinesApiPOSTupdateHomeWidgets:
          Type: HttpApi
          Properties:
            Path: /updateHomeWidgets
            Method: POST
            ApiId: !Ref LinesApi
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000

  HomeWidgetDeleterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HomeWidgetDeleter/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedCodeLayer
      Runtime: python3.9
      Role: arn:aws:iam::107207560024:role/TanzentLambdaRole
      Architectures:
        - x86_64
      Events:
        LinesApiDELETEdeleteHomeWidgetid:
          Type: HttpApi
          Properties:
            Path: /deleteHomeWidget/{id}
            Method: DELETE
            ApiId: !Ref LinesApi
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000

Outputs:
  HttpApiUrl:
    Description: HTTP API endpoint URL
    Value: !Sub https://${LinesApi}.execute-api.${AWS::Region}.amazonaws.com/Prod