AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Template for Tanzent backend application

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  SharedCodeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: codeLayer
      Description: share code layer to be used for all Lines lambda functions
      ContentUri: ../shared-layer/
      CompatibleRuntimes:
        - python3.9
      LicenseInfo: MIT
      RetentionPolicy: Retain

  LinesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:us-east-1:107207560024:userpool/us-east-1_bTOhp8YP9
            IdentitySource: method.request.header.Authorization
      TracingEnabled: false       # Disable tracing

  LinesReaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: LinesReader/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedCodeLayer
      Runtime: python3.9
      Role: arn:aws:iam::107207560024:role/TanzentLambdaRole
      Architectures:
        - x86_64
      Events:
        LinesReader:
          Type: Api
          Properties:
            Path: /line/{lineId}
            Method: get
            RestApiId: !Ref LinesApi
            Auth:
              Authorizer: CognitoAuthorizer

  LinesReaderAllFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: LinesReaderAll/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedCodeLayer
      Runtime: python3.9
      Role: arn:aws:iam::107207560024:role/TanzentLambdaRole
      Architectures:
        - x86_64
      Events:
        LinesReaderAll:
          Type: Api
          Properties:
            Path: /allLines/{userId}
            Method: get
            RestApiId: !Ref LinesApi
            Auth:
              Authorizer: CognitoAuthorizer

  LinesWriterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: LinesWriter/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedCodeLayer
      Runtime: python3.9
      Role: arn:aws:iam::107207560024:role/TanzentLambdaRole
      Architectures:
        - x86_64
      Events:
        LinesWriter:
          Type: Api
          Properties:
            Path: /writer
            Method: post
            RestApiId: !Ref LinesApi
            Auth:
              Authorizer: CognitoAuthorizer

  CirclesFetcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: CirclesFetcher/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedCodeLayer
      Runtime: python3.9
      Role: arn:aws:iam::107207560024:role/TanzentLambdaRole
      Architectures:
        - x86_64
      Events:
        CirclesFetcher:
          Type: Api
          Properties:
            Path: /fetchCircles
            Method: post
            RestApiId: !Ref LinesApi
            Auth:
              Authorizer: CognitoAuthorizer

  LinesDeleterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: LinesDeleter/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedCodeLayer
      Runtime: python3.9
      Role: arn:aws:iam::107207560024:role/TanzentLambdaRole
      Architectures:
        - x86_64
      Events:
        LinesDeleter:
          Type: Api
          Properties:
            Path: /deleteLine/{lineId}
            Method: delete
            RestApiId: !Ref LinesApi
            Auth:
              Authorizer: CognitoAuthorizer

  CircleUpdaterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: CirclesUpdater/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedCodeLayer
      Runtime: python3.9
      Role: arn:aws:iam::107207560024:role/TanzentLambdaRole
      Architectures:
        - x86_64
      Events:
        CircleUpdater:
          Type: Api
          Properties:
            Path: /updateCircle
            Method: put
            RestApiId: !Ref LinesApi
            Auth:
              Authorizer: CognitoAuthorizer

Outputs:
  LinesReaderApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${LinesApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/line/{lineId}"
  LinesReaderAllApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${LinesApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/allLines/{userId}"
  LinesWriterApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${LinesApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/writer"
  LinesDeleterApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${LinesApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/deleteLine/{lineId}"
  CirclesUpdaterApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${LinesApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/updateCircle"
