AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LinesReader

  Sample SAM Template for LinesReader

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  SharedCodeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: codeLayer
      Description: share code layer to be used for all Lines lambda functions
      ContentUri: ../shared-layer/
      CompatibleRuntimes:
        - python3.9
      LicenseInfo: MIT
      RetentionPolicy: Retain

  LinesReaderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: LinesReader/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedCodeLayer
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        LinesReader:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /line/{lineId}
            Method: get
  LinesReaderAllFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: LinesReaderAll/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedCodeLayer
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        LinesReaderAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /allLines/{userId}
            Method: get
  LinesWriterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: LinesWriter/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedCodeLayer
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        LinesWriter:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /writer
            Method: post
  CirclesFetcherFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: CirclesFetcher/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedCodeLayer
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CirclesFetcher:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /fetchCircles
            Method: post


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LinesReaderApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod//user/{userId}/line/{lineId}"
  LinesReaderFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt LinesReaderFunction.Arn
  LinesReaderIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LinesReaderFunctionRole.Arn
  LinesReaderAllApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/all/"
  LinesReaderAllFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt LinesReaderAllFunction.Arn
  LinesReaderAllIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LinesReaderFunctionRole.Arn
  LinesWriterApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/writer/"
  LinesWriterFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt LinesWriterFunction.Arn
  LinesWriterIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LinesReaderFunctionRole.Arn
